1)
CREATE TABLE EDIFICIO(
    CODEDI NUMBER PRIMARY KEY,
    NUMEDI NUMBER NOT NULL,
    RUAEDI VARCHAR2(200),
    BAIEDI VARCHAR2(100)
);

CREATE TABLE APARTAMENTO(
    CODAPT NUMBER PRIMARY KEY,
    NUMAPT NUMBER,
    AREAAPT NUMBER NOT NULL,
    CODEDI NUMBER
);

ALTER TABLE APARTAMENTO
ADD CONSTRAINT FK_APARTAMENTO_CODEDI
FOREIGN KEY (CODEDI) REFERENCES EDIFICIO(CODEDI) ON DELETE CASCADE;

2)
INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (1,1,'bom jardim','bela vista');

INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (2,2,'senhor mauricio','esperanca');

INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (3,3,'padim siso','bela vista');

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (1,1,200,1);

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (2,1,200,2);

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (3,1,200,3);

SELECT *
FROM APARTAMENTO;

3)
CODAPT	NUMAPT	AREAAPT	CODEDI
1	     1	      200      1
2	     1	      200      2
3	     1	      200      3

4)
DELETE FROM EDIFICIO 
WHERE CODEDI = 3;

5)
SELECT *
FROM APARTAMENTO;

CODAPT	NUMAPT	AREAAPT	CODEDI
  2	      1	      200	   2
  3	      1	      200	   2

TODOS OS APARTAMENTOS QUE PEDENDIAM DO EDIFICIO EXCLUIDO, TAMBEM FORAM EXCLUIDOS


6)
DROP TABLE APARTAMENTO;

DROP TABLE EDIFICIO;

7)
CREATE TABLE EDIFICIO(
    CODEDI NUMBER PRIMARY KEY,
    NUMEDI NUMBER NOT NULL,
    RUAEDI VARCHAR2(200),
    BAIEDI VARCHAR2(100)
);

CREATE TABLE APARTAMENTO(
    CODAPT NUMBER PRIMARY KEY,
    NUMAPT NUMBER,
    AREAAPT NUMBER NOT NULL,
    CODEDI NUMBER
);

ALTER TABLE APARTAMENTO
ADD CONSTRAINT FK_APARTAMENTO_CODEDI
FOREIGN KEY (CODEDI) REFERENCES EDIFICIO(CODEDI) ON DELETE SET NULL;

8)
INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (1,1,'bom jardim','bela vista');

INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (2,2,'senhor mauricio','esperanca');

INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (3,3,'padim siso','bela vista');

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (1,1,200,1);

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (2,1,200,2);

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (3,1,200,3);

SELECT *
FROM APARTAMENTO;

CODAPT	NUMAPT	AREAAPT	CODEDI
1	     1	      200      1
2	     1	      200      2
3	     1	      200      3

DELETE FROM EDIFICIO 
WHERE CODEDI = 3;

SELECT *
FROM APARTAMENTO;

CODAPT	NUMAPT	AREAAPT	CODEDI
  1       1       200      1
  2	      1	      200	   2
  3	      1	      200	   null 

TODOS OS APARTAMENTOS QUE PEDENDIAM DO EDIFICIO EXCLUIDO, NAO FORAM EXCLUIDOS

9)
DROP TABLE APARTAMENTO;

DROP TABLE EDIFICIO;

10)
CREATE TABLE EDIFICIO(
    CODEDI NUMBER PRIMARY KEY,
    NUMEDI NUMBER NOT NULL,
    RUAEDI VARCHAR2(200),
    BAIEDI VARCHAR2(100)
);

CREATE TABLE APARTAMENTO(
    CODAPT NUMBER PRIMARY KEY,
    NUMAPT NUMBER,
    AREAAPT NUMBER NOT NULL,
    CODEDI NUMBER
);

ALTER TABLE APARTAMENTO
ADD CONSTRAINT FK_APARTAMENTO_CODEDI
FOREIGN KEY (CODEDI) REFERENCES EDIFICIO(CODEDI);

INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (1,1,'bom jardim','bela vista');

INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (2,2,'senhor mauricio','esperanca');

INSERT INTO EDIFICIO(CODEDI,NUMEDI,RUAEDI,BAIEDI)
VALUES (3,3,'padim siso','bela vista');

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (1,1,200,1);

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (2,1,200,2);

INSERT INTO APARTAMENTO(CODAPT,NUMAPT,AREAAPT,CODEDI)
VALUES (3,1,200,3);

SELECT *
FROM APARTAMENTO;

CODAPT	NUMAPT	AREAAPT	CODEDI
1	     1	      200      1
2	     1	      200      2
3	     1	      200      3

DELETE FROM EDIFICIO 
WHERE CODEDI = 3;

SELECT *
FROM APARTAMENTO;

CODAPT	NUMAPT	AREAAPT	CODEDI
  1       1       200      1
  2	      1	      200	   2
  3	      1	      200	   3 

NAO FOI POSSIVEL A EXCLUSAO, POIS TINHAM TUPLAS EM OUTRA TABELA QUE PEDENDIAM DO EDIFICIO, PARA EXCLUIR
O EDIFICIO, PRIMEIRO TEM QUE EXCLUIR TODOS OS DEPENDENTES